stages:
- name: Build
  steps:
  - runScriptConfig:
      image: maven:3-openjdk-8
      shellScript: mvn package -DskipTests
- name: Build Docker with DIND
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: docker.dev.folio.org/mod-pubsub:${PROJECT_NAME}-latest
      pushRemote: true
      registry: docker.dev.folio.org
    env:
      PROJECT_NAME:
- name: Deploy
  steps:
  - applyAppConfig:
      catalogTemplate: ${PROJECT_ID}:${PROJECT_NAME}-helmcharts-mod-pubsub
      version: 0.1.16
      answers:
        image.repository: docker.dev.folio.org/mod-pubsub
        image.tag: ${PROJECT_NAME}-latest
      targetNamespace: ${PROJECT_NAME}
      name: mod-pubsub
    env:
      PROJECT_NAME:
      PROJECT_ID:  
timeout: 60
notification: {}
